# SAYN sample project. Follow the tutorial for more details:
# https://173tech.github.io/sayn/tutorials/tutorial_part1

required_credentials:
  # List of credential names used by tasks in the project
  - warehouse

# Credential used by sql and autosql tasks
default_db: warehouse
schema_prefix: rightmove

presets:
  crawl:
    type: python
    tags:
      - extract

  gsheet:
    type: python
    tags: 
      - extract

# these groups define the tasks that will be picked up by SAYN
groups:
  models:
    type: autosql
    file_name: "*.sql"
    materialisation: table
    destination:
      table: "{{ task.name }}"

  properties:
    preset: crawl
    module: extract_properties

  locations_gsheet:
    preset: gsheet
    module: gsheet
